# Generated by Django 2.2.2 on 2019-08-14 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('description', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiter', models.CharField(default='', max_length=80)),
                ('is_it_open', models.BooleanField(default=True)),
                ('order_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('surname', models.CharField(default='', max_length=80)),
                ('login', models.CharField(default='', max_length=80)),
                ('password', models.CharField(default='', max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_add', models.DateField()),
                ('phone', models.CharField(default='', max_length=20)),
                ('role', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='role', to='restframeworkcrmfood.Role')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.Meal')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.Table'),
        ),
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('department', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.Department')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.MealCategory'),
        ),
        migrations.CreateModel(
            name='CheckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_fee', models.CharField(default='', max_length=80)),
                ('total_sum', models.CharField(default='', max_length=80)),
                ('meals', models.ManyToManyField(to='restframeworkcrmfood.Meal')),
                ('service_percentage', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.ServicePercentage')),
            ],
        ),
    ]
