# Generated by Django 2.2.2 on 2019-08-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.CharField(default='', max_length=80),
        ),
    ]
