# Generated by Django 2.2.2 on 2019-08-12 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0002_auto_20190731_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_name',
        ),
        migrations.RemoveField(
            model_name='table',
            name='table_id',
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.Table'),
        ),
    ]
