# Generated by Django 2.2.2 on 2019-08-12 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0004_auto_20190812_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_id',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.Meal')),
                ('order', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.Order')),
            ],
        ),
    ]
