# Generated by Django 2.2.2 on 2019-08-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0006_checkmodel_order_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surename',
            new_name='surname',
        ),
    ]
