# Generated by Django 2.2.2 on 2019-09-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0008_orderitem_mealcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(default='Order #', max_length=80),
        ),
    ]
