# Generated by Django 2.2.2 on 2019-09-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0009_order_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkmodel',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.Order'),
        ),
    ]
