# Generated by Django 2.2.2 on 2019-09-04 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0012_auto_20190904_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmodel',
            name='orderedMeals',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='restframeworkcrmfood.OrderItem'),
        ),
    ]
