# Generated by Django 2.2.2 on 2019-09-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0015_auto_20190905_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmodel',
            name='orderedMeals',
            field=models.ManyToManyField(to='restframeworkcrmfood.OrderItem'),
        ),
    ]
