# Generated by Django 2.2.2 on 2019-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0016_auto_20190905_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmodel',
            name='orderedMeals',
            field=models.ManyToManyField(limit_choices_to={'order': 1}, to='restframeworkcrmfood.OrderItem'),
        ),
    ]
