# Generated by Django 2.2.2 on 2019-09-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restframeworkcrmfood', '0018_auto_20190905_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkmodel',
            name='service_fee',
            field=models.CharField(default='5', max_length=80),
        ),
    ]
